### ISSUE TITLE
Resource show date with time instead of date only using Sequelize.DATEONLY

### ISSUE THREAD

**Issue by blurey8** [SoftwareBrothers/admin-bro-sequelizejs#21]
My model:

```js
const MyModel = sequelize.define('my_model', {
    myDate: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },
  },
  ...
);
  return MyModel;
};
```
But the resource still show date with default time (7:00:00 AM) instead of date only.
Like this: `3/29/2020, 7:00:00 AM`
The date field didn't prompt time, though.

I think this is an unexpected behaviour and should be fixed.

In the mean time, is there a way to manipulate myDate properties to show date only?

**Comment by leibowitz** [comment]
This has been fixed in [admin-bro](https://github.com/SoftwareBrothers/admin-bro/pull/513)

Mind trying with the https://www.npmjs.com/package/admin-bro/v/2.8.1-beta.1?
