### ISSUE TITLE
Filtering does not work for resources that include other models

### ISSUE THREAD

**Issue by bakkerthehacker** [SoftwareBrothers/admin-bro-sequelizejs#37]
Using a resource in adminbro that includes another model, filtering on that resource no longer works in 0.5.0.  The filter query gives the error `SequelizeDatabaseError: column reference "name" is ambiguous`.

**Comment by wojtek-krysiak** [comment]
can you paste a schema which causes an error?

**Comment by bakkerthehacker** [comment]
```javascript
const TestModel = sequelize.define('TestModel', {
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
}, {});

const OtherModel = sequelize.define('OtherModel', {
  name: {
    type: Sequelize.STRING,
    allowNull: false,
  },
}, {});

TestModel.hasMany(OtherModel);

TestModel.addScope('defaultScope', { include: [OtherModel] });
```

After adding a resource with `resource: TestModel,` and filtering TestModel on `name`, adminbro gives the error  `SequelizeDatabaseError: column reference "name" is ambiguous` and only gives this error on admin-bro-sequelizejs versions >=0.5.0

**Comment by wojtek-krysiak** [comment]
ok - I know everything - added to backlog
