### ISSUE TITLE
Unhandled BOOLEAN type 

### ISSUE THREAD

**Issue by ZeyadZanaty** [SoftwareBrothers/admin-bro-sequelizejs#4]
Boolean mapping is missing in [ src/property.js](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/property.js)
`const TYPES_MAPPING = [
  ['STRING', 'string'],
  ['TEXT', 'string'],
  ['INTEGER', 'number'],
  ['BIGINT', 'number'],
  ['FLOAT', 'float'],
  ['REAL', 'float'],
  ['DOUBLE', 'float'],
  ['DECIMAL', 'float'],
  ['DATE', 'datetime'],
  ['DATEONLY', 'date'],
  ['ENUM', 'string'],
  ['ARRAY', 'array'],
  ['JSON', 'object'],
  ['JSONB', 'object'],
  ['BLOB', 'string'],
  ['UUID', 'string'],
  ['CIDR', 'string'],
  ['INET', 'string'],
  ['MACADDR', 'string'],
  ['RANGE', 'string'],
  ['GEOMETRY', 'string'],
]`
`['BOOLEAN','boolean']`  should be added to the list

**Comment by empeje** [comment]
🆙 🆙 cc: @wojtek-krysiak 

I've encounter the same problem and have raised the issue here on admin-bro issue tracker https://github.com/SoftwareBrothers/admin-bro/issues/151

**Comment by wojtek-krysiak** [comment]
closed with version @0.2.6

**Comment by empeje** [comment]
Awesome, thanks @wojtek-krysiak 🎉
