### ISSUE TITLE
convertFilter: error on string type on mysql

### ISSUE THREAD

**Issue by delikatessa** [SoftwareBrothers/admin-bro-sequelizejs#5]
Hello, I am using MySql dialect for sequelize and I've noticed that filtering string properties results in an error. `[Op.iRegexp]` is used in convertFilter(), that is a PG specific operator according to https://sequelize.org/master/manual/querying.html#operators. Could you please switch to native SQL `[Op.like]` ? Thank you!

sequelize: 4.44.3
admin-bro: 1.1.4
admin-bro-expressjs: 0.2.0
admin-bro-sequelizejs: 0.2.2
node: 10.15.3

**Comment by wojtek-krysiak** [comment]
fixed with version admin-bro-sequelizejs@0.2.3

**Comment by delikatessa** [comment]
Thank you!
