### ISSUE TITLE
Using MySQL-incompatible ILIKE comparison

### ISSUE THREAD

**Issue by fabiosantoscode** [SoftwareBrothers/admin-bro-sequelizejs#65]
Hey there!

I'm giving adminbro a try for the first time, and I'm loving it! However string filters aren't working. I dug a little deeper and found that it's [using the ILIKE operator](https://github.com/SoftwareBrothers/admin-bro-sequelizejs/blob/master/src/utils/convert-filter.ts#L41) that's not present in MySQL.

Digging into the `node_modules` folder, and changing `build/utils/convert-filter.js` from Op.iLike to Op.like, fixes the crash (but doesn't perform a case insensitive search obviously).

Related: https://github.com/SoftwareBrothers/admin-bro-sequelizejs/issues/5

**Comment by mmilleruva** [comment]
I just ran in to the exact same issue.

**Comment by MoonJR** [comment]
I just ran in to the exact same issue.

**Comment by dziraf** [comment]
I'll update it tomorrow to use `LIKE` instead of `ILIKE` for all database types since that is what it's like in i. e. typeorm adapter. This will make the filter case sensitive though.

**Comment by dziraf** [comment]
The fix is included in the latest `@admin-bro/sequelize@beta`

**Comment by anantaramdas** [comment]
Unfortunately, this fix is not being included to [v2.0.0](https://github.com/SoftwareBrothers/adminjs-sequelizejs/releases/tag/v2.0.0) (which is published to NPM) while was fixed on [v1.3.0-beta.5](https://github.com/SoftwareBrothers/adminjs-sequelizejs/releases/tag/v1.3.0-beta.5). @dziraf is it possible to make either one: include this feature to published release or publish v1.3.0-Beta.5 to NPM, please?
